name: Continuous Integration

on: 
  push:
    branches:
      - '*'

jobs:
  run_tests:
    runs-on: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install requirements
        run: pip install -r requirements.txt 
      - name: Test
        run: python -m pytest tests -v