name: stage

on: 
  pull_request:
    branches:
      - 'develop'

env: 
  HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
  HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
  HEROKU_EMAIL: ${{ secrets.HEROKU_EMAIL }}
  SECRET_KEY: ${{ secrets.SECRET_KEY }}
  TEST_DATABASE_URI: ${{ secrets.TEST_DATABASE_URI }}
  DEV_DATABASE_URI: ${{ secrets.DEV_DATABASE_URI }}
  PROD_DATABASE_URI: ${{ secrets.PROD_DATABASE_URI }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt 
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'
      - name: Install requirements
        run: pip install -r requirements.txt 
      - name: Run Tests
        run: python -m pytest tests -v -p no:warnings
  deploy:
    needs: [build, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: $HEROKU_API_KEY
          heroku_app_name: $HEROKU_APP_NAME
          heroku_email: $HEROKU_EMAIL